export const starters = [
  `Falmer Bar's mozzarella sticks`,
  `Adam Tickell`,
  `tuition fees`,
  `the library`,
  `international students`,
  `joining a sports club`,
  `joining a society`,
  `all of the Full-time Officers`,
  `Falmer House`,
  `The Hatch`,
  `Falmer Bar`,
  `the Co-op`,
  `the 25 bus route`,
  `Falmer train station`,
  `the sports centre on campus`,
  `freedom of speech`,
  `printing on campus`,
  `socialism`,
  `expensive books`,
  `the silent areas in the Library`,
  `the queue in the Co-op`,
  `timetables for the new academic year`,
  `Adam Tickell’s office`,
  `this year’s graduation ceremonies`,
  `Northfield`,
  `Park Village`,
  `being placed in a hotel in Lewes`,
  `East Slope`,
  `Lewes Court`,
  `Stanmer Court`,
  `Swanborough`,
  `Brighthelm`,
  `The Badger`,
  `URF`,
  `UniTV`,
  `Union Council`,
  `the President`,
  `the Activities Officer`,
  `the Welfare Officer`,
  `the Undergraduate Education Officer`,
  `the Postgraduate Education Officer`,
  `the Society & Citizenship Officer`,
  `your dissertation`,
  `undergraduates`,
  `postgraduates`,
  `BSMS students`,
  `rooms in Falmer House`,
  `lecture theatres`,
  `Eduroam`,
  `seminar rooms`,
  `study spaces`,
  `your flatmates`,
  `your bedroom`,
  `your nearest bus stop`,
  `slides from lectures`,
  `Facebook`,
  `Twitter`,
  `Snapchat`,
  `feedback on your work`,
  `Theresa May`,
  `Jo Johnson, Minister for Universities & Science`,
  `the National Student Survey`,
  `Study Direct`,
  `The National Union of Students`,
  `The Tab`,
  `Teh Univursity of Susex`,
  `Turnitin`,
  `your favourite lecturer`,
  `your presentation group`,
  `SKINT at East Slope Bar`,
  `West Street`,
  `almond croissants from the Union shop`,
  `Sanjeev Bhaskar, University Chancellor`,
  `vegetarian meal options`,
  `procrastinating`,
  `talking about your gap year`,
  `The Meeting House`,
  `Sussex Uni Hoodies`,
  `arguing with your flatmates`,
  `IT Services`,
  `Brexit`,
  `Brighton Pier`,
  `exam desks`,
  `hogging a computer`,
  `Eat Central`,
  `Global Studies students`,
  `NUS Extra cards`,
  `the 10% Co-op discount`,
  `Prince Harry`,
  `Active US`,
  `a swimming pool on campus`,
  `The Falmer Bar deli`,
  `trying to get to your 9am lecture on time`,
  `Library Square`,
  `Caroline Lucas MP`,
  `Churchill Square`,
  `essays`,
  `your reading list`,
  `renting somewhere in Brighton & Hove`,
  `the Brighton Bike Share bikes`,
  `Lewes Road`,
  `pretending you’ve done the reading for your seminar`,
  `science students`,
  `arts students`,
  `The Clubhouse`,
  `your PhD Supervisor`,
  `Instagram`,
  `seagulls`,
  `reading The Badger`,
  `listening to URF`,
  `reading The Tab`,
  `watching UniTV`,
  `the Union Shop`,
  `finding a parking space on campus`,
  `memes`,
  `capitalism`,
  `Elm Grove`,
  `all the hills in Brighton`,
  `the sea`,
  `the meaning of life`,
  `your revision notes`,
  `members of sports clubs`,
  `members of societies`,
  `members of your sports club`,
  `members of your society`,
  `people that sit near me in lectures`,
  `people who don’t move down the bus`,
  `volunteering`,
  `your student loan`,
  `your student debt`,
  `the stairs up to the Library`,
  `library fines`,
  `your module options`,
  `voting in Students’ Union elections`,
  `Adam Tickell’s Instagram feed`,
  `smashing your phone screen`,
  `the N25`,
  `the 25X`,
  `exams on a Saturday`,
  `recording lectures automatically`,
  `going to lectures`,
  `the mould in your flat`,
  `your employability`,
  `learning something new`,
  `sitting on the beach`,
  `the cost of living`,
  `talking about politics`,
  `talking about sport`,
  `your tutor’s office hours`,
  `Bramber House`,
  `taking hot drinks into the Library`,
  `connecting to Eduroam`,
  `the University`,
  `the Students’ Union`,
  `walking across the stage at graduation`,
  `the information you get before you start here`,
  `building work on campus`,
  `stanmer Park`,
  `more trees on campus`,
];

export const enders = [
  `handed out at graduation`,
  `submerged in the Falmer House moat`,
  `banned from 9am lectures`,
  `available from The Hatch`,
  `compulsory if you live in Northfield`,
  `forced to wait while three full 25 buses go past your stop`,
  `cheaper`,
  `free`,
  `far more expensive`,
  `easier`,
  `harder to find`,
  `more accessible`,
  `replaced with even more stairs`,
  `replaced with grants from the government`,
  `put to a national referendum`,
  `included in tuition fees`,
  `banned`,
  `powered by Falmer Bar’s nachos`,
  `destroyed instead of East Slope Bar`,
  `part of every module`,
  `replaced by full communism`,
  `available via Sussex Direct`,
  `doomed to stay in the Co-op queue for eternity`,
  `made available at least two months in advance`,
  `displayed in Arts A`,
  `limited to first years`,
  `mentioned on Open Days`,
  `the only thing you can search for on eduroam`,
  `at the Freshers Fair`,
  `moved to Brighton Pier`,
  `the campus Snapchat filter`,
  `available on Snapchat`,
  `live-streamed daily`,
  `compulsory`,
  `on the frontpage of The Badger every fortnight`,
  `performed at East Slope Bar’s Open Mic Night`,
  `banned from campus`,
  `permitted on campus`,
  `only allowed in Falmer House`,
  `available online`,
  `a compulsory module`,
  `used as an example in every lecture`,
  `in the end of year exam`,
  `discussed in the Houses of Parliament`,
  `tested on students`,
  `delivered within three working days`,
  `shouted at the start of every lecture`,
  `on the front cover of the prospectus`,
  `the proudest achievement on the Vice-Chancellor’s CV`,
  `enjoyed with a slice of cake from Room 76`,
  `optional`,
  `the subject of your thesis`,
  `built on campus`,
  `given more funding`,
  `given less funding`,
  `required to graduate`,
  `prioritised more`,
  `prioritised less`,
  `twice as big`,
  `half the size`,
  `invited to Adam Tickell’s birthday party`,
  `permitted as a reason for missing lectures`,
  `available 24/7`,
  `the fancy dress theme at Pryzm`,
  `discounted with an NUS Extra card`,
  `awarded a First`,
  `removed by campus security`,
  `nationally recognised`,
  `preserved for eternity`,
  `only for postgraduates`,
  `encouraged`,
  `discouraged`,
  `only available off-peak`,
  `an Olympic sport`,
  `considered taboo`,
  `part of Freshers Week`,
  `celebrated in Library Square`,
  `delivered to your next lecture`,
  `appreciated by graduate employers`,
  `a life goal`,
  `written on the side of a red bus`,
  `added to your CV`,
  `used for exams`,
  `recommended as a study tool`,
  `grounds for extra marks`,
  `banned on health grounds`,
  `on your reading list`,
  `in the Library’s core collection`,
  `made to (finally) take your flat’s rubbish out`,
  `made to do the washing up`,
  `the same price as a Freddo`,
  `harder`,
  `advertised as a study space`,
  `recommended to new students`,
  `memorialised with a statue in Library Square`,
  `only available online`,
  `only available on Mondays`,
  `sold in the Union Shop`,
  `the subject of a meme`,
  `punished by expulsion`,
  `the subject of the VC’s speech at graduation`,
  `distributed in Library Square`,
  `dictated by market forces`,
  `worth more`,
  `worth less`,
  `acceptable`,
  `adopted as the new Sussex Uni mascot`,
  `condemned`,
  `part of a bushtucker trial`,
  `broadcast on URF`,
  `better`,
  `worse`,
  `ignored`,
  `avoided`,
  `on your bucket list`,
  `covered in seagull poo`,
  `communicated via emoji`,
  `rewarded with pizza`,
  `sold on ebay`,
  `assessed by Adam Tickell`,
  `diverted along the seafront`,
  `put off until next term`,
  `interesting`,
  `funny`,
  `studied by scientists`,
  `smoother`,
  `faster`,
  `warmer`,
  `cosier`,
  `quarantined`,
  `valued more`,
  `supported`,
  `open later`,
  `promoted`,
  `encouraged`,
  `done in fancy dress`,
  `subject to a formal dress code`,
  `projected onto Falmer House`,
  `displayed in every window on campus`,
  `made into a film`,
  `the title of your autobiography`,
  `personalised with your name`,
  `on your degree certificate`,
  `an accepted currency on campus`,
  `something to be proud of`,
  `something to brag to your friends at other unis about`,
  `refundable`,
  `more equally distributed`,
  `a research specialism at Sussex`,
  `scrutinised`,
  `made into a documentary`,
  `immortalised in a scale model`,
  `given a lifetime membership to Falmer Bar`,
];
